# Generated by Django 6.1.1 on 2026-09-14 16:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=500)),
                ('original_title', models.CharField(blank=True, default='', max_length=500)),
                ('overview', models.TextField(blank=True, default='')),
                ('poster_path', models.CharField(blank=True, default='', max_length=500)),
                ('backdrop_path', models.CharField(blank=True, default='', max_length=500)),
                ('release_date', models.CharField(blank=True, default='', max_length=50)),
                ('vote_average', models.FloatField(default=0.0)),
                ('vote_count', models.IntegerField(default=0)),
                ('genres', models.JSONField(blank=True, default=list)),
                ('runtime', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='MovieList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('color', models.CharField(default='#f5c518', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MovieListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('plan_to_watch', 'Plan to Watch'), ('watching', 'Watching'), ('completed', 'Completed'), ('dropped', 'Dropped')], default='plan_to_watch', max_length=20)),
                ('user_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('user_notes', models.TextField(blank=True, default='')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='movies.movielist')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_items', to='movies.movie')),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('list', 'movie')},
            },
        ),
    ]
