# Generated by Django 6.1.1 on 2026-09-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movielist_options_movie_budget_movie_cast_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='crew',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='movie',
            name='original_language',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='movie',
            name='production_countries',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='movie',
            name='release_status',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
