# Generated by Django 6.1.1 on 2026-09-20 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_crew_movie_director_movie_original_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movielist',
            name='icon',
            field=models.CharField(default='Film', max_length=50),
        ),
        migrations.AddField(
            model_name='movielist',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
    ]
