# Generated by Django 6.1.1 on 2026-09-27 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_add_icon_and_favourite_to_movielist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('notes', models.TextField(blank=True, default='')),
                ('is_watched', models.BooleanField(default=False)),
                ('google_event_id', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_watches', to='movies.movie')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
